### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Marcosreuquen** [cynthiadaubert/final-modulo-tres#1]
Buenas, Cynthia!
Lo estuve viendo y creo que deberías aumentar los px del breakpoint porque se rompe en resoluciones bajas. Podrías darle un @media de 769 aprox que es la resolución stardard de las tablets.
Te dejo captura de lo que me refiero: 
![image](https://user-images.githubusercontent.com/75027556/134988123-d2d6351c-8a80-407f-a2a1-2be10351208f.png)

Cualquier cosa no dudes en consultar por discord para ayudarte.
Saludos.

**Comment by cynthiadaubert** [comment]
@Marcosreuquen
Hola! ok, buenisimo! cometí el error de maquetarlo solo en las dimensiones que decía la versión de figma y no lo chequeé en mi celular a ver como se veía. Muchas gracias!

**Comment by Marcosreuquen** [comment]
Buenas, Cynthia! 
Veo qe estuviste resolviendo otros issues posteriores y que te ha quedado muy bien!
Quedaron pequeños detalles de margins/paddings en la versión mobile. Tal vez, para darle una resolución, podrías ver de en los input del form quitarle los márgenes derecho e izquierdo, como también al nav del footer, reemplazándolos por un margin auto.
Sobre los mobiles fold y iphone5 te diría que lo mires con mucho cuidado porque tienen pantallas muy especiales que suelen romper cualquier maquetado. Para este tipo de situaciones se suele hacer código más minucioso agregando más breakpoints o usando otras herramientas.
Te felicito por el camino y haber llegado hasta acá. 
Saludos!
