### ISSUE TITLE
Review #2 -  Body con margin y rotura en modo mobile.

### ISSUE THREAD

**Issue by FacundoEG** [cynthiadaubert/final-modulo-tres#2]
Hola Cyn! además de la review que te mando Marcos, noto que la pagina tiene un borde blanco rodeandola:

![image](https://user-images.githubusercontent.com/79592789/135781410-72ef1095-4f6d-408a-811a-e4814fa567f4.png)

![image](https://user-images.githubusercontent.com/79592789/135781414-5cc9b109-41e8-4acd-9e99-a3134a55c1c0.png)

La verdad que eso se soluciona muy fácil poniéndole un "margin: 0" al body en si, te recomiendo que lo soluciones de esa manera ya que es la mas simple!

Después en el header, noto que lo que mas rompe el diseño es el margin que tiene la imagen principal, fíjate de aprovechar las diferentes propiedades de "display:flex" , ayuda mucho para resolver eso sin tener que usar márgenes fijos, ya que la verdad en un futuro no va a ser tan escalable! esto mismo lo podes usar para las otras partes de la page.

Te pediría que revises esas cosas y además veas un poco el tema del tamaño en si de los elementos dentro de cada sección y priorices que queden acomodados y "aguanten" los cambios de la resolución.

Te mando un saludo y esperamos esos cambios!

Suerte!

**Comment by cynthiadaubert** [comment]
@FacundoEG  

Hola, gracias por el comentario! Estaba intentando quitar los bordes con margin 0 pero lo estaba poniendo en otro lugar, por eso no me funcionaba. Ahí revisé lo de los márgenes y se los saqué a casi todo, la verdad que me compliqué demasiado ajustando todo a ojo.

**Comment by FacundoEG** [comment]
Si Cyn! vi que se lo estabas poniendo a muchos elementos, acodarte que poniéndose al body directamente con CSS te ahorras ese tema! 

Volví a darle una ojeada a la page y te quedo muchísimo mejor distribuido todo! te voy a cerrar el issue porque ya resolviste este tópico.

Te mando un saludo y suerte! dale que ya aprobas el desafío!
