### ISSUE TITLE
issues #3

### ISSUE THREAD

**Issue by giulianaerro** [cynthiadaubert/final-modulo-tres#3]
Hola cynthia! sumandome a la review de facu, fijate que muchas de tus cosas se rompen porque colocas mucho margin para los costados. Por ahi a veces es mas preferible un padding. En el caso de abrir en una tables tu pagina se rompe. en la parte de la imagen de kitty, podes eliminar el margin de esa imagen y jugar mas con display: flex y margin: 0 auto; para centrar las cosas

**Comment by cynthiadaubert** [comment]
@giulianaerro Ok, buenisimo! ahi le quité los márgenes a casi todo y lo arreglé solo con flex. Traté de usar padding en los lugares que me parecía necesario. Gracias!!
