### ISSUE TITLE
Review 4(?

### ISSUE THREAD

**Issue by FerDR89** [cynthiadaubert/final-modulo-tres#4]
Buenas Cynthia.

Me sumo a lo de mis compas, estuve revisando la parte desktop y el margin que le pones a la foto de gatito te rompe el diseño (quizás lo visualizaste en un monitor grande y por eso tanto margin)

![image](https://user-images.githubusercontent.com/74626765/135848764-4a8f0039-a129-43fb-a8a4-3c968664787f.png)

Podes probar quitándole al margin a todos los elementos dentro de "container-main" y manejar todos esos elementos internos desde ese mismo contenedor.

Con esta propiedad en el contenedor:     justify-content: space-between; alineas los elementos a los bordes del mismo y después con padding los vas "metiendo" hacia adentro hasta alinearlos a tu gusto.

**Comment by cynthiadaubert** [comment]
@FerDR89 Hola, ok, buenisimo! Si, estaba usando el monitor y quise arreglar todo con margin pero en las otras resoluciones se rompía asi que solamente usé flex y algo de padding. Ahora lo probé en varias resoluciones y en desktop y se ve bien, salvo en Iphone5/SE y galaxy fold pero no sé por qué pasa en esos dos únicamente.
